# @package _global_
tag: BCI2A_TCN_LR_baseline

model:
  _target_: models.tcn_baseline.TCNClassifier
  in_channels: 22
  num_classes: 2

  # TCN hyperparameters
  hidden_channels: 64
  num_levels: 5
  kernel_size: 3
  dropout: 0.1
  classification_type: "bc"